/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-12-17 17:00:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Map;
import Model.Cart;
import Model.Items;
import Model.TaiKhoan;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Model.TaiKhoan");
    _jspx_imports_classes.add("Model.Cart");
    _jspx_imports_classes.add("Model.Items");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Thanh Toán</title>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<!--theme-style-->\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />	\r\n");
      out.write("<!--//theme-style-->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Bonfire Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<!--fonts-->\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Exo:100,200,300,400,500,600,700,800,900' rel='stylesheet' type='text/css'>\r\n");
      out.write("<!--//fonts-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("				<script type=\"text/javascript\">\r\n");
      out.write("					jQuery(document).ready(function($) {\r\n");
      out.write("						$(\".scroll\").click(function(event){		\r\n");
      out.write("							event.preventDefault();\r\n");
      out.write("							$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);\r\n");
      out.write("						});\r\n");
      out.write("					});\r\n");
      out.write("				</script>\r\n");
      out.write("<script>$(document).ready(function(c) {\r\n");
      out.write("	$('.alert-close').on('click', function(c){\r\n");
      out.write("		$('.message').fadeOut('slow', function(c){\r\n");
      out.write("	  		$('.message').remove();\r\n");
      out.write("		});\r\n");
      out.write("	});	  \r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script>$(document).ready(function(c) {\r\n");
      out.write("	$('.alert-close1').on('click', function(c){\r\n");
      out.write("		$('.message1').fadeOut('slow', function(c){\r\n");
      out.write("	  		$('.message1').remove();\r\n");
      out.write("		});\r\n");
      out.write("	});	  \r\n");
      out.write("});\r\n");
      out.write("</script>				\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  ");
 
  Cart cart=(Cart) session.getAttribute("cart");
if(cart==null)
{
	cart=new Cart();
	session.setAttribute("cart", cart);
	}
TaiKhoan tk= null;
if(session.getAttribute("user")==null)
{
response.sendRedirect("/DemoDisplaynew/login.jsp");
	}

      out.write("\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("   <!--header-->\r\n");
      out.write("   		<div class=\"container\">\r\n");
      out.write("			<div class=\"products\">\r\n");
      out.write("					<h2 style=\"color: black;\" class=\" products-in\">Danh sách sản phẩm đã chọn</h2>\r\n");
      out.write("					<div class=\"content\">\r\n");
      out.write("				<div class=\"content-top\">\r\n");
      out.write("					<div class=\"content-top-in\">\r\n");
      out.write("				 ");
for(Map.Entry<String,Items> list: cart.getCartItems().entrySet()) { 
      out.write("\r\n");
      out.write("						<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a><img  src=\"images/");
      out.print(list.getValue().getSanpham().getHinhAnh() );
      out.write("\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>");
      out.print(list.getValue().getSanpham().getTenSP() );
      out.write("</a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("									<p class=\"dollar\"><span class=\"in-dollar\">");
      out.print(list.getValue().getSanpham().getGia() );
      out.write("</span><span>VND</span></p>\r\n");
      out.write("						\r\n");
      out.write("									</div>\r\n");
      out.write("									<center><h5 style=\"color: red;\">Số lượng=");
      out.print(list.getValue().getSoLuong());
      out.write("</h5></center>\r\n");
      out.write("									<br>\r\n");
      out.write("									<div>\r\n");
      out.write("											 <center><a href=\"CartController?command=sum&MaSP=");
      out.print(list.getKey());
      out.write("\"><button><span> + </span></button></a></center>\r\n");
      out.write("									 <center><a href= \"CartController?command=sub&MaSP=");
      out.print(list.getKey());
      out.write("\"><button ><span> - </span></button></a></center>\r\n");
      out.write("							\r\n");
      out.write("									  \r\n");
      out.write("									  </div>\r\n");
      out.write("									 <center><li><a href= \"CartController?command=remove&MaSP=");
      out.print(list.getKey());
      out.write("\">Xóa khỏi giỏ hàng</a></li></center>\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						");
} 
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<br>\r\n");
      out.write("					 <div class=\"total\">\r\n");
      out.write("	                        	<div class=\"total_left\"><h3 style=\"color: black;\">Tổng tiền : </h3></div>\r\n");
      out.write("	                        	<div ><h3>");
      out.print(cart.sumTotalCart() );
      out.write("</h2></div>\r\n");
      out.write("	                        	<div class=\"clearfix\"> </div>\r\n");
      out.write("	                        </div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("  				\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"account\">\r\n");
      out.write("			<h2 class=\"account-in\">Thanh Toán</h2>\r\n");
      out.write("				<form action=\"CheckoutController\" method=\"POST\">\r\n");
      out.write("			\r\n");
      out.write("				<div>\r\n");
      out.write("					<span class=\"word\">Địa chỉ *</span>\r\n");
      out.write("					<input type=\"text\" name=\"address\">\r\n");
      out.write("				</div> 	\r\n");
      out.write("				\r\n");
      out.write("					<div>\r\n");
      out.write("					<span>Hình thức</span>\r\n");
      out.write("				<select name=\"payment\">\r\n");
      out.write("				<option value=\"BIDV\">BIDV</option>\r\n");
      out.write("				<option value=\"ARGIBANK\">ARGIBANK</option>\r\n");
      out.write("				<option value=\"OCEANBANK\">OCEANBANK</option>\r\n");
      out.write("				<option value=\"ACB\">ACB</option>\r\n");
      out.write("				<option value=\"VCB\">VIETCOMBANK</option>\r\n");
      out.write("					<option value=\"OCB\">OCB</option>\r\n");
      out.write("					<option value=\"ViettinBank\">ViettinBank</option>\r\n");
      out.write("				</select>\r\n");
      out.write("    	</div>\r\n");
      out.write("    	<input type=\"submit\" value=\"Thanh Toán\"> \r\n");
      out.write("				</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>		<!---->\r\n");
      out.write("<!-- footer -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("</body>\r\n");
      out.write("</head>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
