/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-12-13 05:17:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.SanPham;
import DAO.SanPhamDAO;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar", Long.valueOf(1544248510000L));
    _jspx_dependants.put("jar:file:/D:/20130297_WEB/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DemoDisplaynew/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.4.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1420530628000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DAO.SanPhamDAO");
    _jspx_imports_classes.add("Model.SanPham");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("				<!---->\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"content\">\r\n");
      out.write("				<div class=\"content-top\">\r\n");
      out.write("					<h3 class=\"future\">ĐẶC SẮC</h3>\r\n");
      out.write("					<div class=\"content-top-in\">\r\n");
      out.write("				\r\n");
      out.write("					<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a><img  src=\"images/oppof9.png\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Điện thoại Oppo F9 64GB</a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM01  class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">7690000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>	\r\n");
      out.write("															\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a ><img  src=\"images/ncd1.jpg\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Nồi cơm điện tử Kangaroo KG566</a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM02 \" class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">799000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("							<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a><img  src=\"images/tiviLG.jpg\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Smart TV LG 43inch 4K Ultra HD</a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM01 \" class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">7990000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a ><img  src=\"images/aokhoat.jpg\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Áo Hoodie Tay Dài Có Mũ Super Man</a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM04 \" class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">170000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a><img  src=\"images/Dell.png\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Dell Precision 5510 Core i7</a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM03 \" class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">31999000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a><img  src=\"images/tainghe.jpg\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Tai nghe nhét tai BYZ S389 </a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM01 \" class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">60000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a><img  src=\"images/20biet.jpg\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Nếu tôi biết được khi còn 20</a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM05 \" class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">48000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a><img  src=\"images/balo.jpg\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Balo Thời Trang Xiaomi Mi Casual </a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM04 \" class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">279000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						</div>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!---->\r\n");
      out.write("				<div class=\"content-middle\">\r\n");
      out.write("					<h3 class=\"future\">NHÃN HIỆU</h3>\r\n");
      out.write("					<div class=\"content-middle-in\">\r\n");
      out.write("					<ul id=\"flexiselDemo1\">		\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("            		<script type=\"text/javascript\">\r\n");
      out.write("		$(window).load(function() {\r\n");
      out.write("			$(\"#flexiselDemo1\").flexisel({\r\n");
      out.write("				visibleItems: 4,\r\n");
      out.write("				animationSpeed: 1000,\r\n");
      out.write("				autoPlay: true,\r\n");
      out.write("				autoPlaySpeed: 3000,    		\r\n");
      out.write("				pauseOnHover: true,\r\n");
      out.write("				enableResponsiveBreakpoints: true,\r\n");
      out.write("		    	responsiveBreakpoints: { \r\n");
      out.write("		    		portrait: { \r\n");
      out.write("		    			changePoint:480,\r\n");
      out.write("		    			visibleItems: 1\r\n");
      out.write("		    		}, \r\n");
      out.write("		    		landscape: { \r\n");
      out.write("		    			changePoint:640,\r\n");
      out.write("		    			visibleItems: 2\r\n");
      out.write("		    		},\r\n");
      out.write("		    		tablet: { \r\n");
      out.write("		    			changePoint:768,\r\n");
      out.write("		    			visibleItems: 3\r\n");
      out.write("		    		}\r\n");
      out.write("		    	}\r\n");
      out.write("		    });\r\n");
      out.write("		    \r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/jquery.flexisel.js\"></script>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!---->\r\n");
      out.write("				<div class=\"content-bottom\">\r\n");
      out.write("					<h3 class=\"future\">CÓ TRÊN WEBS</h3>\r\n");
      out.write("					<div class=\"content-bottom-in\">\r\n");
      out.write("					<ul id=\"flexiselDemo2\">			\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a><img  src=\"images/oppof9.png\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Điện thoại Oppo F9 64GB</a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM01  class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">7690000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>	\r\n");
      out.write("															\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a ><img  src=\"images/ncd1.jpg\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Nồi cơm điện tử Kangaroo KG566</a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM02 \" class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">799000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a><img  src=\"images/aokhoat.jpg\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Áo Hoodie Tay Dài Có Mũ Super Man</a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM04 \" class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">170000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a><img  src=\"images/Dell.png\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Dell Precision 5510 Core i7</a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM03 \" class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">31999000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a><img  src=\"images/tainghe.jpg\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Tai nghe nhét tai BYZ S389 </a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM01 \" class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">60000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a><img  src=\"images/20biet.jpg\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Nếu tôi biết được khi còn 20</a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM05 \" class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">48000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a><img  src=\"images/balo.jpg\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Balo Thời Trang Xiaomi Mi Casual </a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM04 \" class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">279000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-3 md-col\">\r\n");
      out.write("							<div class=\"col-md\">\r\n");
      out.write("								<a><img  src=\"images/tiviLG.jpg\" alt=\"\" /></a>	\r\n");
      out.write("								<div class=\"top-content\">\r\n");
      out.write("									<center><h5><a>Smart TV LG 43inch 4K Ultra HD</a></h5></center>\r\n");
      out.write("									<div class=\"white\">\r\n");
      out.write("										<a href=products.jsp?ChuyenMuc=CM01 \" class=\"hvr-shutter-in-vertical hvr-shutter-in-vertical2\">Xem thêm</a>	\r\n");
      out.write("										<p class=\"dollar\"><span class=\"in-dollar\">7990000</span><span>Đ</span></p>\r\n");
      out.write("										<div class=\"clearfix\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>							\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					\r\n");
      out.write("					</ul>\r\n");
      out.write("					<script type=\"text/javascript\">\r\n");
      out.write("		$(window).load(function() {\r\n");
      out.write("			$(\"#flexiselDemo2\").flexisel({\r\n");
      out.write("				visibleItems: 4,\r\n");
      out.write("				animationSpeed: 1000,\r\n");
      out.write("				autoPlay: true,\r\n");
      out.write("				autoPlaySpeed: 3000,    		\r\n");
      out.write("				pauseOnHover: true,\r\n");
      out.write("				enableResponsiveBreakpoints: true,\r\n");
      out.write("		    	responsiveBreakpoints: { \r\n");
      out.write("		    		portrait: { \r\n");
      out.write("		    			changePoint:480,\r\n");
      out.write("		    			visibleItems: 1\r\n");
      out.write("		    		}, \r\n");
      out.write("		    		landscape: { \r\n");
      out.write("		    			changePoint:640,\r\n");
      out.write("		    			visibleItems: 2\r\n");
      out.write("		    		},\r\n");
      out.write("		    		tablet: { \r\n");
      out.write("		    			changePoint:768,\r\n");
      out.write("		    			visibleItems: 3\r\n");
      out.write("		    		}\r\n");
      out.write("		    	}\r\n");
      out.write("		    });\r\n");
      out.write("		    \r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<ul class=\"start\">\r\n");
      out.write("					<li ><a href=\"#\"><i></i></a></li>\r\n");
      out.write("					<li><span>1</span></li>\r\n");
      out.write("					<li class=\"arrow\"><a href=\"#\">2</a></li>\r\n");
      out.write("					<li class=\"arrow\"><a href=\"#\">3</a></li>\r\n");
      out.write("					<li class=\"arrow\"><a href=\"#\">4</a></li>\r\n");
      out.write("					<li class=\"arrow\"><a href=\"#\">5</a></li>\r\n");
      out.write("					<li ><a href=\"#\"><i  class=\"next\"> </i></a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /content.jsp(161,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listslidebannerLogo}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /content.jsp(161,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("listLogo");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("	\r\n");
            out.write("						<li><img src=\"images/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${listLogo.slidebannerLogoName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"/></li>\r\n");
            out.write("						\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
