/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-12-17 17:00:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("		<div class=\"footer\">\r\n");
      out.write("			<div class=\"footer-top\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"col-md-4 footer-in\">\r\n");
      out.write("						<h4><i> </i>Mua hàng nhanh</h4>\r\n");
      out.write("						<p>Mẹo: Quý khách hàng có thể truy cập vào thanh tìm kiếm ở đầu trang để có thể tìm kiếm những sản phẩm cần mua.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-4 footer-in\">\r\n");
      out.write("						<h4><i class=\"cross\"> </i>Thanh toán nhanh</h4>\r\n");
      out.write("						<p>Webisite được ứng dụng thanh toán trực tuyến nên quý khách hàng có thể thõa sức mua hàng mà không lo đến việc khó khăn trong thanh toán. </p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-4 footer-in\">\r\n");
      out.write("						<h4><i class=\"down\"> </i>Nguồn mở</h4>\r\n");
      out.write("						<p>Website được chạy trên nhiều nền tảng, với trụ sở chính ở: 145 tt Dầu Tiếng,huyện Dầu Tiếng, Tỉnh Bình Dương</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!---->\r\n");
      out.write("			<div class=\"footer-middle\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"footer-middle-in\">\r\n");
      out.write("						<h6>Thông tin website</h6>\r\n");
      out.write("						<p>Số 145 tt Dầu Tiếng,huyện Dầu Tiếng, Tỉnh Bình Dương\r\n");
      out.write("						<br>Hotline: 0353799530.\r\n");
      out.write("						</p>\r\n");
      out.write("						\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"footer-middle-in\">\r\n");
      out.write("						<h6>Thông tin</h6>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\">Về chúng tôi</a></li>\r\n");
      out.write("							<li><a href=\"#\">Chăm sóc khách hàng</a></li>\r\n");
      out.write("							\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"footer-middle-in\">\r\n");
      out.write("						<h6>Dịch vụ khách hàng</h6>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"contact.jsp\">Liên hệ chúng tôi</a></li>\r\n");
      out.write("							<li><a href=\"#\">Thanh toán trực tuyến</a></li>\r\n");
      out.write("							<li><a href=\"#\">Sản phẩm mới nhất</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"footer-middle-in\">\r\n");
      out.write("						<h6>Tài khoản của tôi</h6>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"login.jsp\">Tài khoản của tôi</a></li>\r\n");
      out.write("							<li><a href=\"#\">Lịch sử đơn hàng</a></li>\r\n");
      out.write("							<li><a href=\"wishlist.jsp\">Danh sách sản phẩm</a></li>\r\n");
      out.write("							<li><a href=\"#\">Bản tin</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"footer-middle-in\">\r\n");
      out.write("						<h6>Ngoài ra</h6>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\">Nhãn hiệu</a></li>\r\n");
      out.write("							<li><a href=\"#\">Phiếu quà tặng</a></li>\r\n");
      out.write("							<li><a href=\"#\">Chi nhánh</a></li>\r\n");
      out.write("							<li><a href=\"#\">Đặc biệt</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"clearfix\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<p class=\"footer-class\">\r\n");
      out.write("			Web design by PHAM HOANG KHUONG\r\n");
      out.write("			<br>\r\n");
      out.write("			&copy;2022 Website sales </p>\r\n");
      out.write("			<script type=\"text/javascript\">\r\n");
      out.write("						$(document).ready(function() {\r\n");
      out.write("							/*\r\n");
      out.write("							var defaults = {\r\n");
      out.write("					  			containerID: 'toTop', // fading element id\r\n");
      out.write("								containerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("								scrollSpeed: 1200,\r\n");
      out.write("								easingType: 'linear' \r\n");
      out.write("					 		};\r\n");
      out.write("							*/\r\n");
      out.write("							\r\n");
      out.write("							$().UItoTop({ easingType: 'easeOutQuart' });\r\n");
      out.write("							\r\n");
      out.write("						});\r\n");
      out.write("					</script>\r\n");
      out.write("				<a href=\"#\" id=\"toTop\" style=\"display: block;\"> <span id=\"toTopHover\" style=\"opacity: 1;\"> </span></a>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
